### ISSUE TITLE
Some ost files do not appear as options for backup

### ISSUE THREAD

**Issue by BrianPassante** [HoffmannTom/outlookbackupaddin#16]
2 of my 4 ost mail files don't appear as options to include in the backup.  These 2 email accounts are imap rather than exchange mail accounts, but outlook 2016=office 365 saves the mail accounts as .ost files in the same directory location as my other 2 exchange accounts.  Any ideas?

**Comment by HoffmannTom** [comment]
Hello,
ost files are not suitable for backups because recovery is not always possible (e.g. doesnt work on a different computer:
There is a registry key to also show ost files but i dont recommend this way.
As you use IMAP, the client only caches emails. If your computer breaks down, all the data should still be available on server side. So maybe client-side backup is not necessary(?)
You can force outlook to use a pst file for IMAP account (as it was with outlook 2010). You must create a pst file manually, set it as default and then move your mail items to the new default pst files.
I found a german explanation here: https://www.mailhilfe.de/beitrag-so-vermeiden-sie-den-verlust-ihrer-kontakte-und-kalendereintrge-durch-die-benut-3926-html
maybe chrome or google translation is suitable for this.
Further information is also archived in this thread overview: 
https://archive.codeplex.com/?p=outlookbackupaddin (just search for "ost" on this site).

Greetings,
Thomas

**Comment by HoffmannTom** [comment]
Hello,
ost files are not suitable for backups because recovery is not always possible (e.g. doesnt work on a different computer:
There is a registry key to also show ost files but i dont recommend this way.
As you use IMAP, the client only caches emails. If your computer breaks down, all the data should still be available on server side. So maybe client-side backup is not necessary(?)
You can force outlook to use a pst file for IMAP account (as it was with outlook 2010). You must create a pst file manually, set it as default and then move your mail items to the new default pst files.
I found a german explanation here: https://www.mailhilfe.de/beitrag-so-vermeiden-sie-den-verlust-ihrer-kontakte-und-kalendereintrge-durch-die-benut-3926-html
maybe chrome or google translation is suitable for this.
Further information is also archived in this thread overview: 
https://archive.codeplex.com/?p=outlookbackupaddin (just search for "ost" on this site).

Greetings,
Thomas

**Comment by vulliw** [comment]
Outlook 2016 Backup Add-In 1.7.0 no longer works with X64 !
 I have installed it, not give an error message
 but there is no backup in Outlook 2019 x64 (ribben)

In Outlook 2019 x32 it just works
 Please help me

vulliw
