### ISSUE TITLE
When Backup Encounters an Error: Prompt to Close [Enhancement]

### ISSUE THREAD

**Issue by BLeenheer** [HoffmannTom/outlookbackupaddin#4]
In an effort to make this addin more user friendly, options need to be provided to the user when the backup fails due to an error. 

As far as I can tell, the application will exit when there is no error. When there **is** an error, the application just sits there and waits for the user to hit the close button on the window. While this is important for error reporting, user's who are not tech savvy may be unsure how to handle the fact that the window isn't closing or offering a way to handle the problem. 

My suggestion (and/or request) is that you add a simple message indicating that there was a problem with the backup, and a simple "Okay" button to close the application window. This would improve the UX significantly in the event that something goes wrong.

**Comment by HoffmannTom** [comment]
Hello,
in the development version a hint was added which informs the user to close the window
manually. As errors shouldnt occur in normal case, I didnt add a separate button because
it would have to be disabled in normal operation and users might want to click it without waiting till backup finishs.

Regards,
Thomas
