### ISSUE TITLE
Error messages unrelated to actual error.

### ISSUE THREAD

**Issue by Mallorca1946** [HoffmannTom/outlookbackupaddin#41]
I had the destination for backups set as on the E disk.  Due to a system update the disk became reassigned to F.  When Outlook Backup ran I got a bunch of error messages related to an instance of Outlook not being found, rather than the backup destination.  On checking Settings I found the destination had been blanked out.  Entering the new destination fixed the problem.  Confusing and not intuitive.

**Comment by HoffmannTom** [comment]
Hello,
i manually changed the destination path and get the following messages:
13:17:40 Starting backup...please wait...
13:17:40 Check whether outlooks is still running ...
13:17:40 No outlook process found
13:17:40 Ensure only one instance running ...
13:17:40 Check whether target directory exists...
13:17:40 Can't create directory E:\OutlookBak\: Das Gerät ist nicht bereit.

13:17:40 One or more errors occurred. Please check the messages above and close this window manually.

"no outlook process" means that all outlook programs closed and therefore the pst files should not be locked any more. This is important in order to copy the files.
Maybe this message was misleading(?)

Otherwise please post your messages. So far i cant see any wrong message.

Greetings,
Thomas

**Comment by HoffmannTom** [comment]
Quick note:
You can change the backup path in the registry at:
HKEY_CURRENT_USER\Software\CodePlex\BackupAddIn\Settings\
Because the GUI doesn't let you choose a non-existent path.

**Comment by Mallorca1946** [comment]
Those were not the messages I observed.
>  Because the GUI doesn't let you choose a non-existent path.
That might be the important factor.  After the OS had reassigned the drive letters (initially unknown to me) I checked and found the destination field was entirely blank.  So I guess the s/w logic went slightly askew.  Thanks for the feedback.

**Comment by HoffmannTom** [comment]
Hello,
I modified the path via registry but the wrong path just stays.
There is also just one place in the sources where the path is modified.
All in all it's quite an edge case.
If you can provide a snipped of the logfile, i could try to figure out what happened.
Otherwise I will close that case in 2 weeks.

Thanks! Thomas

**Comment by Mallorca1946** [comment]
Log file ???

**Comment by HoffmannTom** [comment]
well.... i referred to the log output (not really a file).
If you can provide a screenshot or could copy&paste the messages, I will take a look at it.

Regards, Thomas

**Comment by Mallorca1946** [comment]
I made a number of updates to my PC, updated drivers, BIOS and s/w, and only after the error in outlookbackupaddin occurred did I realise that the drive letter assignments had been changed.  I looked at settings for the app and the destination was blank.  So for a test I went into the registry and set the destination to blanks.  This resulted in these messages...
                                                                                                                   
![addin1jpg](https://user-images.githubusercontent.com/51863793/64538056-db624280-d313-11e9-9410-9992dbe43b35.jpg)
![addin2jpg](https://user-images.githubusercontent.com/51863793/64538136-fb920180-d313-11e9-9d22-e2a2ddcf27e0.jpg)

My OP gave a confusing description of the messages.

**Comment by HoffmannTom** [comment]
Hello,
the error message makes sense because without path the program tries to copy the pst files to the current directory. As that program is run by outlook, the current folder is the installation folder of outlook. (usually c:\Program Files\Microsoft Office\...)
This folder has not write permission to normal users (only to users with elevated privileges).
The messages "A required privilege ..." tells you that you are not allowed to write to that current directory.
Thanks for the hint with the cleaner.
So far, everything makes sense and the last message is generated by windows.
It is better to keep the original microsoft error message because you can google that term to find further information.
Greetings, Thomas
