### ISSUE TITLE
Including Archive PST in backup

### ISSUE THREAD

**Issue by m-schmitt** [HoffmannTom/outlookbackupaddin#45]
Outlook normally doesn't keep the AutoArchive archive PST attached in the folder list.  It may be attached _during_ an AutoArchive, by option Advanced > AutoArchive > AutoArchive Settings > During AutoArchive: Show archive folder in folder list, but even then it will disappear after the AutoArchive is complete.

How can you set the Backup addin to back up the archive PST?

You can manually attach to the archive PST and then select it in the Backup settings. But that only lasts as long as the archive is attached. If you detach it and then check the settings it will be gone again.

**Comment by HoffmannTom** [comment]
Hello,
currently there are several options possible:
1) Keep the archive pst attached
2) Even if you detach the archive pst afterwards, the backup will still take place.
    The pst is not visible in the settings window but as long as you dont save a new configuration,
    the backup settings are still preserverd 
   (please uncheck the "backup all" option because this will overwrite the pst files with the currently attached ones)
   You can check the registry at Computer\HKEY_CURRENT_USER\Software\CodePlex\BackupAddIn\Settings\ to see which items are backed up.
3) Use a post backup command file (examples are provided in the setup zip)

Is one of the above solutions suitable?

Greetings, Thomas

**Comment by m-schmitt** [comment]
I thought I was doing option #2; I had set it up previously that way. I stopped using "backup all" to stop backing up the .OST since it was always still in use.

I see the problem: when you Reset the backup date to force a backup and Save, that also changes the item list, losing the (hidden) Archive.pst item.

...which means, method #2 is not reliable, at least not without being very careful about settings.

I tried option #3, which works, but it creates a command prompt window while it is running.  What are my options for the post-backup command? Is it shelling to cmd.exe specifically or can I use any executable command line I want? I might have more control if I code the post-backup in REXX, KixTart, PowerShell or something else.

**Comment by HoffmannTom** [comment]
Hello,
you can run any file which is associated with an executable file.
More information is available at:
https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.startinfo?view=netframework-4.8
E.g. if extension .php is registered to run with php.exe, you should also be able to run a php file.
You can also use PowerShell and compile it to an exe file. This would work without any filetype association.

Greetings, Thomas

**Comment by m-schmitt** [comment]
When I enter `c:\windows\system32\cmd.exe /c start /min "C:\Users\mschmitt7\Documents\Scripts\Backup Archive PST.cmd"`
the result is 
 `Error executing c:\windows\system32\cmd.exe /c start /min "C:\Users\mschmitt7\Documents\Scripts\Backup Archive PST.cmd": The system cannot find the file specified`
but the same command works in Windows Run.

I don't know that this would be my final solution (I'm leaning towards a KixTart script) but first I need to figure out why it doesn't accept an executable command.

**Comment by HoffmannTom** [comment]
Hello,
currently there is no support for parameters. Only the filename can currently be maintained.
"C:\Users\mschmitt7\Documents\Scripts\Backup Archive PST.cmd" itself should work.
You currently can't run a file and add parameters to it because there is only one field available.
If you dont want to see that cmd box, you can use PowerShell and compile it to exe (not tried yet).
An alternative way would be to modify the cmd-association and add /min in general.
Greetings, Thomas

**Comment by m-schmitt** [comment]
The solution was to create a VB exe:

```Visual Basic
Module BackupArchivePST
    Sub Main()
        Dim FileToCopy = "archive.pst"
        Dim OutlookFiles = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments) + "\Outlook Files\"
        Dim source = OutlookFiles + FileToCopy
        Dim target = OutlookFiles + "Backup\" + FileToCopy + ".bak"
        My.Computer.FileSystem.CopyFile(source, target, True)
    End Sub
End Module
```

**Comment by HoffmannTom** [comment]
Hello,
great that it worked out :)
There are many paths to the goal.
