### ISSUE TITLE
silent mode

### ISSUE THREAD

**Issue by RoRoStar** [HoffmannTom/outlookbackupaddin#49]
Hello,
Thanks for this great addin ! 
Is there a way to start a silent mode backup (no window showing up) ?
Another functionality that would be great is to execute a backup (in silent mode) while outlook is running (using VSS) to backup files in background.

Maybe this could be usefull, I don't know : 
https://github.com/alphaleonis/AlphaVSS

Let me know !
Thank you.
Regards

**Comment by HoffmannTom** [comment]
Hello,
actually you can run any program after outlook exits.
You can also use scripts to run after quitting outlook instead of backupExecutor.exe
A wrapper skript which hides the execution of the program would meet your requirements.

Regarding VSS:
The program must support VSS in order to create a consistent pst file.
Outlook doesnt support VSS and thus the file might be corrupted.
I am aware that SQL-server and other server programs are working with VSS.
They listen to a signal and when VSS starts they flush their cashes and create a consistent state.

As outlook doesnt register at the VSS writer, making a backup with a perhaps inconsistent file
is not a good option.

greetings, Thomas

**Comment by RoRoStar** [comment]
Hi,

Ok thank you for reply.
About VSS the alternative could be requesting the PST from the last
existing VSS snapshot.

Thank you
regards.

Le jeu. 19 déc. 2019 à 18:40, HoffmannTom <notifications@github.com> a
écrit :

**Comment by HoffmannTom** [comment]
Hello,
the problem of consistency still persists. Office doesn't guarantee that the (previous) file versions are consistent.
You also get further problems:
- The last shadow copy might be old and thus doesnt contain the expected mails
- pst file might be located in a folder, which is not covered by VSS
- The user might have disabled VSS or excluded certain files and folders
As long as office doesnt support VSS, the only safe way to get a consistent backup is when 
outlook is closed.

If you want to do a VSS backup of your pst files during the day, you could also use the task scheduler. You wouldn't need this add-in. The downside is the consistency as explained above.

You can use the tool vshadow to create a skript for this purpose:
https://docs.microsoft.com/en-us/windows/win32/vss/vshadow-tool-examples

Greetings, Thomas
