### ISSUE TITLE
Disabled in Outlook 2019 x64: Outlook states the plugin caused it to crash

### ISSUE THREAD

**Issue by M0dK1nG** [HoffmannTom/outlookbackupaddin#52]
Worked great and then after a couple of months and updates, the plugin was automatically disabled by Outlook stating it had caused a crash and would not let me disable it. I have the latest version and even uninstalled, gutted, and reinstalled just to make sure.

**Comment by HoffmannTom** [comment]
Hello,
sometimes it takes a while till the .Net framework is loaded. Outlook keeps track of the loading times of every add-in. If outlook thinks that the loading time is too high, it will deactivate the add-in.
The information is stored within the registry.
So in order to reactivate the add-in, you must clean up some registry values.

Some general information is listed at: https://docs.microsoft.com/en-us/previous-versions/office/jj228679(v=office.15)?redirectedfrom=MSDN

Please open the registry editor and go to:
HKEY_CURRENT_USER\Software\Microsoft\Office\<Version>\Outlook\Resiliency
Delete entries which are related to "Codeplex.BackupAddIn".

You can prevent future disabling by settings a registry key:
https://support.microsoft.com/en-us/help/2758876/add-ins-are-user-re-enabled-after-being-disabled-by-office-programs
--> HKEY_CURRENT_USER\Software\Microsoft\Office\<Version>\Outlook\Resiliency\DoNotDisableAddinList

Greetings, Thomas

**Comment by HoffmannTom** [comment]
Hello,
do you have any feedback on this issue?
Is your problem solved?
Greetings, Thomas

**Comment by M0dK1nG** [comment]
Thank you very much for the response. I will look into your suggestions and
get back to as soon as possible.

**Comment by HoffmannTom** [comment]
Hello,
do you have any updates on this issue?
Greetings, Thomas

**Comment by M0dK1nG** [comment]
I completely forgot about this and had just removed it. I reinstalled it
and found this upon the launching Outlook. The enable button does nothing.
[image: image.png]

**Comment by M0dK1nG** [comment]
I manually removed the entries from
HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Outlook\Resiliency\CrashingAddinList
&
HKEY_CURRENT_USER\Software\Microsoft\Office\16.0\Outlook\Resiliency\DisabledItems
&
Now the add-in loads. We will see what happens....

**Comment by HoffmannTom** [comment]
Hello,
to prevent getting disabled again, I recommend to add the key 
HKEY_CURRENT_USER\Software\Microsoft\Office<Version>\Outlook\Resiliency\DoNotDisableAddinList
--> new RegDWord: Codeplex.BackupAddIn --> Value 1
as shown in the microsoft link above.
Greetings, Thomas

**Comment by M0dK1nG** [comment]
Thank you, I will.
