### ISSUE TITLE
Confirmation dialog before backup

### ISSUE THREAD

**Issue by xelan** [HoffmannTom/outlookbackupaddin#63]
Hi @HoffmannTom! Would it be possible to add a confirmation dialog before the backup is started (e.g. `Backup now` / `Later`)? One of our customers is annoyed that the backup is always executed immediately (and cannot be cancelled) if he closes Outlook by accident.

Thank you very much, best regards
Andreas

**Comment by viking2** [comment]
@Andreas,
I had the same issue https://github.com/HoffmannTom/outlookbackupaddin/issues/58, and it can already be accomplished. 
In the Settings, I set the backup countdown to 10 sec. When I close Outlook, a countdown window opens up. Just close it (X) if you do not want to backup now.

**Comment by HoffmannTom** [comment]
Hello,
I also recommend the solution, suggested by viking2.
Please set the timeout and check if the customers gets along with it. During the countdown, the user can just click on [x]
and cancel the planned backup.
The backup is only triggered, if the planned backup interval is reached. So the backup is intentionally starting because the time interval elapsed. So "immediately" in your case means, that the backup was planned for this time. Maybe you can also check, whether the backup interval is suitable for the customer.
Greetings, Thomas

**Comment by xelan** [comment]
Ah ok, thanks for the quick response. I'll try that and show this solution to our customer.

Best regards Andreas

**Comment by xelan** [comment]
Thanks again, our customer likes the solution with the backup timer :smile: :+1:
