### ISSUE TITLE
Outlook 2016 BACKUP Ribbon not showing

### ISSUE THREAD

**Issue by SatisfactoryBug** [HoffmannTom/outlookbackupaddin#65]
I did check the Registry "LoadBehavior"=dword:00000003

Load 2016 but the BACKUP Tab still missing also Outlook 2016 COM Add-Ins i put Tick then Click OK recheck COM Add-Ins it show Inactive Application Add-ins so i close 2016 then Reload 2016 and same thing no BACKUP TAB and  Inactive Application Add-ins i also did do Repair and Remove then Install same thing

I checked Registry of
HKEY_CURRENT_USER\Software\Microsoft\Office\Outlook\Addins\Codeplex.BackupAddIn
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Office\Outlook\Addins
HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Office\Outlook\Addins\Codeplex.BackupAddIn
Amy idea why ??

Thank

**Comment by SatisfactoryBug** [comment]
it ok now, sorted as uninstall 2016 and install outlookbackupaddin FIRST then install 2016,

it very odd that HoffmannTom
/
outlookbackupaddin to be installed first.... then 2016, strange......

**Comment by HoffmannTom** [comment]
Helllo,
usually you can or should install the add-in after outlook.
Sometimes outlook might mark the add-in as permanently disabled.
There are some registry keys which can contain this disabled-flag:
HKEY_CURRENT_USER\SOFTWARE\Microsoft\Office\<version>\Outlook\Resiliency\DisabledItems
HKEY_CURRENT_USER\Software\Microsoft\Office\<version>\Outlook\Resiliency\CrashingAddinList

There are also registry keys to disable this disable-flags:
HKEY_CURRENT_USER\SOFTWARE\Microsoft\Office\<version>\Outlook\Resiliency\DoNotDisableAddinList\

Instead of HKey_Current_User there are similar settings under HKLM

Perhaps you uninstalled outlook and thus deleting the registry keys and after new installation everything worked.

Greetings,
Thomas

**Comment by SatisfactoryBug** [comment]
Thank, if ever other time it happen, about the DoNotDisableAddinList is that a a Key or String or Binary or DWORD (32-bit) Value etc

**Comment by HoffmannTom** [comment]
Hello, 
DoNotDisableAddinList is the key / path in the registry.
The value is of type Reg_DWORD and has the Prog-ID as value.
For details see: https://docs.microsoft.com/en-us/office/vba/outlook/concepts/getting-started/support-for-keeping-add-ins-enabled

Greetigs, Thomas

**Comment by Fran978** [comment]
Hello, 
outlook 2019 on win10 x64 here.
Once I used regsvr32 "C:\Program Files (x86)\Microsoft Office\Office12\ADDINS\outbak.dll" to make it appear.
On another version I used backupexecutor /register. Now it gives error:"Object reference not set to an instance of an object"
The issue is created on a new user on a machine where the addin was previously installed on an old user

**Comment by HoffmannTom** [comment]
Hello,
to register the add-in, use "backupexecutor /register". Just registering the dll won't have any effect.
Does the error show up once at startup or when doing any specific action?

**Comment by Fran978** [comment]
The error shows up when registering after "Adding Subkeys"
On this machine Office has been upgraded in the past from 2007 to 2019. being Conscious that this has caused me many problems with other machines, now I'm trying to reinstall win10 as it has often solved various issues.
Repairing the addin inst or office has been useless.

**Comment by Fran978** [comment]
Solved! 
While reinstalling win10 had no effect, I noticed while using backupexecutor /register it detected Office 32 bit, while 64 was installed. So I uninstalled 64 bit version and installed 32 et voilà!
I believe the cause was a precedent installation of office2007 32bit

**Comment by HoffmannTom** [comment]
great to hear!
The add-in is using the registry to find the outlook installation.
Maybe there are some remaining registry keys, pointing to a 32-bit outlook.exe.
