### ISSUE TITLE
Backup of OST files

### ISSUE THREAD

**Issue by udobehm** [HoffmannTom/outlookbackupaddin#91]
Good day,

thanks first of all for your free tool! I like the idea of doing automated backups of my Outlook data.

However I have a concern: As far as I can see your tool is saving the OST file 1:1 to the export folder. What I would like to get is a PST file out of the OST data file. Could your tool maybe use the integrated export function in Outlook in order to save the whole OST as a PST file or would there be another option to directly save it as PST file instead of OST?

Also I would like to know whether new backups replace the old backup in the saving folder. If not would it be possible to configure the tool to always delete the old file and save the newest backup as the only backup file being saved? In case I wanted to add the date to the backup, how would I need to enter this information in your tool? Would I still be able to only keep the last or maybe the last 5 recent backups that the BackupAddin was creating?

You think it could be possible to specify a backup interval of more than 31 days?

Thanks
Udo

**Comment by HoffmannTom** [comment]
Hello Udo,
please check out this wiki page: https://github.com/HoffmannTom/outlookbackupaddin/wiki/Files-are-not-shown-for-backup(%3F)
The ost files are cache files and are not suitable for backups. Details are mentioned in the page above.

Regarding the naming: You can use environment-variables in the target path field (e.g. %DATE% which I never tried).
Another option is to use the post-backup-cmd feature. Sample scripts are provided in the subfolder sample-scripts.

31 days for the last backup is already quite long (or even too long), right?
Currently, you could modify the settings within the registry, but I would recommend at least weekly backups.

Hope this information helps!
Thomas

**Comment by udobehm** [comment]
Hi Thomas,

thanks for the information! Does that mean that your tool is useless for me?

I only use Outlook for getting access to my Outlook.com profile. What I was hoping I could achieve with your tool is to backup everything once in a while (as PST file).

As it looks I cannot do this however, just with the help of your tool.

Is there no way you could use the integrated export function in Outlook to make Outlook backup/export my data as a PST file maybe every 31 days (this is enough for me :)

Thanks

What about the file naming? Does your tool overwrite/replace the saved file every time?

Udo

**Comment by HoffmannTom** [comment]
Hello Udo,

if you use POP3, you get a pst-file that can be backed up (if this is feasible and reasonable for you).

The file is overwritten per default but you can use the post-backup-cmd function to add arbitrary retention methods.
Examples are available in the subfolder. The example "keep_n_backups.bat" matches your requirement.

Greetings,
Thomas

**Comment by udobehm** [comment]
Hi Thomas,

POP3 is unfortunately not feasible to me. I mostly want to save my calendars, email, tasks and contacts. As far as I know these items (besides emails) are not being synced with POP3...

You do not see any way to make your tool work with the OST file? Maybe you could find a way to convert it or maybe use the export function of Outlook to export the things as PST file?

**Comment by HoffmannTom** [comment]
Hello Udo,
I think it is best to step back and think about the goal you want to achieve or which risk you want to mitigate.
If you use IMAP, all emails remain on the server. If your local disc crashes, you can just set up a new system and connect to the IMAP account without losing anything. 
If the server crashes, the provider is in charge and should have measures to prevent data loss.

About OST:
The OST file is just a cache and usually doesn't contain all emails. So even if you export "everything", this doesn't mean that all emails are exported. You would need to modify the cache first, download all content from the IMAP server, and then export everything. This shouldn't be done in the background automatically because it changes some settings in your outlook.

POP3 on the other hand, usually deletes the emails on the server (if not configured otherwise). Therefore, it makes sense to back up the PST-file to prevent data loss when your local disc or system crashes.

Greetings, Thomas

**Comment by udobehm** [comment]
Hi Thomas,

my goal is to backup especially the calendars, contacts and tasks in case I or the server is messing up something with this data. How could I recall them?

So I thought of doing automated backups. But of course, what I would probably rather need are PST-files instead of OST ones.

I don't really like connecting my Outlook account a second time in order to be able to export a PST file of my account.

You see ne possibility that your tool could do this or you know of any tool that is capable of doing so? I would love to have an automated solution for this - so I don't have to backup all my data manually all the time with the help of the export tool of Outlook.

Thanks for your help...
Udo

**Comment by HoffmannTom** [comment]
Hello Udo,
backup is only a means for a purpose. So preventing data loss by accidental deletion is a point.
For this reason, outlook uses a "deleted items" folder and even if you delete this folder, there is a secondary recycle bin (at least if you use an Exchange account). So you need to delete it two to three times to lose data.

Data loss by the provider might be a reason. In general, you should use a trusted provider whom you trust to have a good backup and restore procedure. I am not aware of any data loss in recent years and they have more measures in place than a private user.

You need to estimate the risk/probability and damage of losing data.

Anyway, you can backup your ost files with the plugin (via a registry switch) but ost files are not suitable for restoring on another computer. You can find a commercial converter from ost to pst online. I don't know how well this works and therefore you would need to do a test run to make sure it works and nothing gets lost.

You would also need to set the cache configuration to download all messages (and lose one benefit of using IMAP). Otherwise, the ost files only contain emails from the last x days/months by default.

For backing up merely emails, another option would be to set an Outlook rule and copy every email to a pst file. This doesn't work for calenders, contacts, etc. though.

I hope this information helps.

Greetings, Thomas

**Comment by udobehm** [comment]
Hi Thomas,

the idea that I have is to restore calendar items or contacts that might have become accidentially changed. E. g. if I change a date that I didn't want to change, change a phone number or contact information, save (update) the appointment or the contact and cannot refer to the old contact or appointment anymore... Therefore I would like to have a backup.

If it is not possible to backup these things with your tool, do you know of any (easy to handle and easy to install and manageable) tool that I could use for this scenario? I still wished you were able to implement a function that does exactly the extract option of Outlook - to save data into a pst file on a scheduleable timeframe.

If you know any other tool that could handle this I am thankful for your advice...

Thanks
Udo

**Comment by HoffmannTom** [comment]
Hello Udo,
thanks for hinting out your backup reasons, makes sense.

Exporting to a pst file would be a topic for another add-in, unfortunately.

There are other tools around, e.g. https://www.ubackup.com/email/ which can export to pst

I am sure there are other tools out there.

Greetings,
Thomas

**Comment by udobehm** [comment]
This is costing $40 a year 🙈

**Comment by HoffmannTom** [comment]
My add-in is only free because I spend my leisure time on development and maintenance.
If you have to pay for the employees and infrastructure, then you can't give away the software for free.
You can decide if the provided features and services are worth it. They charge around $ 3.33 per month.
You can search for something else of course too.

**Comment by udobehm** [comment]
Okay. I don't think that there is any free tool available for my purpose. You see no chance of implementing this function? Maybe sort of as a macro that automatically is doing the steps that you have to do manually if you want to export data from Outlook as PST. Or is that too hard or too much time consuming for you to implement inside your tool? Would of course be very handy if your tool could handle this...

**Comment by HoffmannTom** [comment]
Hello Udo,
exporting folders to a PST is another topic and out-of-scope of this add-in.
It would require different settings, folder selection, backup mechanism, backup logic, etc.

**Comment by udobehm** [comment]
Ok, thanks for your help!
